"""add_questions_table

Revision ID: d5ad644d90f7
Revises: 20260517_0001
Create Date: 2026-05-26 00:59:06.559079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5ad644d90f7'
down_revision: Union[str, Sequence[str], None] = '20260517_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_evaluations_id'), 'evaluations', ['id'], unique=False)
    op.create_index(op.f('ix_interview_reports_id'), 'interview_reports', ['id'], unique=False)
    op.create_index(op.f('ix_interviews_id'), 'interviews', ['id'], unique=False)
    op.create_index(op.f('ix_live_sessions_id'), 'live_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_live_sessions_interview_id'), 'live_sessions', ['interview_id'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_live_sessions_interview_id'), table_name='live_sessions')
    op.drop_index(op.f('ix_live_sessions_id'), table_name='live_sessions')
    op.drop_index(op.f('ix_interviews_id'), table_name='interviews')
    op.drop_index(op.f('ix_interview_reports_id'), table_name='interview_reports')
    op.drop_index(op.f('ix_evaluations_id'), table_name='evaluations')
    # ### end Alembic commands ###
